version: '3.8'
 
services:
  web:
    env_file:
      - .env
    build: ./dbcsv # Changed build context
    command: bash -c 'uvicorn dbcsv.app.main:app --host 0.0.0.0 --port 80'
    volumes:
      - .:/app # Updated volume mount
    ports:
      - 80:80
